# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a01debfe0c58c74c5883bfa3a1fffa7c2e8322bb1d9b966aa2d4ec1fe3c47e19f9b03bbb88e8cf4a4c9046c820b3e847529cea340188629b30f9d0167b449ab

test:
  secret_key_base: 3603d968aeb86f2aafd20297158ec6a991a31f2dec7512bbbcd7e7c09ecef09b9db9ac485c2f4c36f0fc12270c56c8b49508a4f613e6d8a0a7a4f9104fcce942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
